## Server properties
server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/studentdb?current_schema=public
    driverClassName: org.postgresql.Driver
    username: user
    password: password

## Database properties for debezium
student:
  datasource:
    databasename: studentdb
    host: localhost
    port: 5433
    username: user
    password: password

## ElasticSearch properties
elasticsearch:
  host: localhost
  port: 9200
  username:
  password:

## Logging properties
logging: 
  file: logs/student-cdc-relay.log
  level:
    org.springframework.web: INFO