
version: "3.0"
services:
  database:
    image: postgres:latest
    ports:
      - 5433:5433
    expose:
      - 5433
    environment:
      - POSTGRES_PASSWORD=demopassword
      - POSTGRES_USER=demouser
      - POSTGRES_DB=liquibasedemo
    command: -p 5433